### ISSUE TITLE
Had to use a Cookie header

### ISSUE THREAD

**Issue by fredzica** [alex314159/PerlFinanceQuoteBloomberg#7]
Hello.

I could make this work only by adding a 'Cookie' header. Doesn't look like a durable solution though. Any idea on avoiding this?

Thanks.

**Comment by alex314159** [comment]
Hi, it's working very erratically for me too, I keep getting into captcha. I know very little about Perl so hard to find a better solution. Can you share your Cookie solution? thanks,

**Comment by fredzica** [comment]
I just added a `cookie` http header with a value I grabbed from the same header by navigating to bloomberg quote page with a browser.
I'm wondering if a robust solution to this would be to use a headless browser, so it would generate cookies just like the browser we use, and be cycling the user-agent to make the usage patterns more natural.

**Comment by alex314159** [comment]
can you share your cookie code?

agree something like Selenium is the way forward - I'll have a look at https://metacpan.org/pod/Selenium::Remote::Driver

**Comment by fredzica** [comment]
Sure. Sorry that I cannot help with the implementation, I'm currently overwhelmed with other tasks.
Here goes the declaration of the variable that contains the http headers
```
    my @ns_headers = (
	    'User-Agent' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36', 
#      'User-Agent' => 'Mozilla/5.0 (Linux; Android 6.0.1; SM-G532G Build/MMB29T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.83 Mobile Safari/537.36', 
      'Accept' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
      'Accept-Encoding' => 'br', 
      'Accept-Language' => 'en-US,en;q=0.9',
      'Cookie' => 'bbAbVisits=; _reg-csrf=s%3Abeiro2fr6yDhYT1UbBWKdN4I.3rHFdz49qG4t7UF30KQ3weWuDEnfV4feCcNkY0BpgZ0; _reg-csrf-token=7VTbASCv-b5EjnK4q0EhdaAOj4rKEx_QlnxM; agent_id=32481640-35eb-46f3-9a36-f286dbfe9cfe; session_id=1981de61-a1b4-4f72-aaed-29bb508d73b6; session_key=b9cab98960cfc255b50d2556ed262157761acf06; _user-status=anonymous; bb_geo_info={"country":"US","region":"US"}|1571248634895; _gcl_au=1.1.1726577321.1570643835; _user_newsletters=[]; bdfpc=004.7282107926.1570643835028; _pxvid=39e85df8-eabe-11e9-b15e-0242ac12000a; _pxde=55ea6c4ae7fac9b65de3e3294ead1b4196b5897e9cca205a6e38506042e1d90d:eyJ0aW1lc3RhbXAiOjE1NzA2NTA1Njk3ODUsImZfa2IiOjAsImlwY19pZCI6W119; notice_behavior=none; permutive-session=%7B%22session_id%22%3A%22ea50b626-74bc-4892-b9c5-b5a0e66b1524%22%2C%22last_updated%22%3A%222019-10-09T19%3A32%3A00.088Z%22%7D; permutive-id=7d79e993-6fbd-42a4-b808-88b8309fc4b0; bbAbVisits=; __tbc=%7Bjzx%7Dt_3qvTkEkvt3AGEeiiNNgLInO7D5q-gNNVMYXaomFA2PMn8RDJYCbbD0v3FQwh5JoF2YFoNbzIciTP5GaZdl7Olyvla-utZCr3u2Idlnxj_Rd0cZApFfxEpVLgqJPn0ojylU0Z664w9lha1BgkmqDg; __pat=-14400000; __pvi=%7B%22id%22%3A%22v-2019-10-09-15-27-56-189-zxArGrb2lq6M5tHj-d22356553525b0b6eb9b1ec44e609a58%22%2C%22domain%22%3A%22.bloomberg.com%22%2C%22time%22%3A1570649520446%7D; xbc=%7Bjzx%7DmC1EG7Vp2x-b744jJOaYuXwpUEc_9qOgc-zkolGtMvyAMh8E7P12r-eF6pe8ljatdh5vpf3do1EJLRy5V87EY9kRpCf7mYszQmQ9CXx9N2f4v0YiXfN8cD3f5J1HuZ3mBsVacZYqfnIfb4NqeIWEFwzgyo6_uM6Bmz00PDJkWGw30flLxTyB3997m2CsLDH57aWfkw4co3SpbaTakmahVoV7y1_H-R06EV4wuhPFk2ek-VLldYfws69_bQHoEuXz-p0rU7z-aNO8xtjHpC96mTawE8o7efuD6xFd4tq23XqiEYzaxwoG9SweVrnV2_HSkqw5J6lEisaUk_cH1uAcRJ2QEbHDKNt5GhA53b272UV0OBseA2ri_7iKQdHaFRt_Pix2-dSvxmZ0OPSEJiZ0labdeUSmmdjzK9NDxao2kz0; _px2=eyJ1IjoiNzU0ZTA5YTAtZWFjYi0xMWU5LTlmZWItOWJiMjQ1NTY2MThlIiwidiI6IjM5ZTg1ZGY4LWVhYmUtMTFlOS1iMTVlLTAyNDJhYzEyMDAwYSIsInQiOjE1NzA2NTA3ODc1NjksImgiOiJjN2MxOTA5OTIxM2UwZmIwYWRhODgwNzA5MjhmNmRmZDBlMjU1ZDk0MDE4YjY2NDA2ZDllYjczNmJiNTZkOTIzIn0=; _px3=4a300cb3ee50dc28e8dd39391191ce239f622b0052cf8d85e23e4e0fa66cdf8d:KNJk6033mkUn8dQXkS3s3AaXLd/k4U1dxwt/HtX/+Jlm/wd6BIqNX0gTImrQNl032egQ93soMPKXJVXoHo/KxA==:1000:JELhFNUphuO88sTQ5G95bl9bKNQcAzN8UYo/AvMix6j6dZ/CapDusbofLJi3CoEL//tq9Z+LAKg9O/00Y+3Z5AkXwVS6TDk0PATjv0h2okuvp30RthcYEdheNOi1sY4fuaUK3czGKp/XU2GWjz93wiK6l2t7rhhxehlSDUFZi7Q=; cookieConsent=firstVisit|; cPixel=required|performance|advertising|linkedin-insights|media-shop|; __ncuid=4e6c215a-12db-465a-aa11-4189045443ef; _user-ip=71.233.149.118',
      'cache-control' => 'max-age=0', );
```

**Comment by alex314159** [comment]
Thank you - unbelievably that worked for me too with the same header!

**Comment by realrosid** [comment]
Hi. I also used the same Header and was able to get it to work.
Will you push an update for this or do you have another option in mind?

**Comment by alex314159** [comment]
Just did. No idea why this works, but no time or expertise for something better!

**Comment by realrosid** [comment]
It stopped working this morning, using my manual change or your released one. 
Seems like they found out ;-).

**Comment by fredzica** [comment]
It works because it's a real cookie generated from a normal visit with a web browser. Simply visit the quote page of bloomberg and grab the cookie header that your browser generates.
The cookie will eventually expire, and it's controlled by the server, so they may have criteria for invalidating the session. The robust solution to this is generating a cookie on every visit, for instance with a headless browser as we discussed couple weeks ago.

**Comment by fredzica** [comment]
The cookie serves as a way for the server to identify a user session btw

**Comment by realrosid** [comment]
Hi. Thanks for the info. Could you please explain where I can get the data from and where I have to put it? Somewhere in line 46? Do I have to change something?
Thanks in advance!

**Comment by alex314159** [comment]
almost a year later, code updated with instructions as to how to get your
own cookies
